# Generated by Django 4.2.9 on 2026-03-17 05:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('photo', 'Profile Photo')], max_length=20)),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_url', models.CharField(max_length=1000)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
            options={
                'unique_together': {('worker', 'doc_type')},
            },
        ),
    ]
