# Generated by Django 4.2.9 on 2026-03-17 05:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerIDCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('qr_code_data', models.CharField(max_length=500)),
                ('pdf_s3_key', models.CharField(max_length=500)),
                ('pdf_s3_url', models.CharField(max_length=1000)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
        ),
    ]
