# Generated by Django 4.2.9 on 2026-03-17 05:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('maid', 'Maid / Housekeeping'), ('cook', 'Cook'), ('driver', 'Driver'), ('gardener', 'Gardener'), ('security', 'Security Guard'), ('childcare', 'Child Care'), ('eldercare', 'Elder Care'), ('other', 'Other')], max_length=20)),
                ('other_work_type', models.CharField(blank=True, max_length=50)),
                ('years_experience', models.IntegerField(default=0)),
                ('languages_known', models.CharField(max_length=200)),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('live_in', 'Live-in')], max_length=20)),
                ('preferred_area', models.CharField(blank=True, max_length=100)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
    ]
